name: Docker Build and Push to Hugging Face

on:
  push:
    branches:
      - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Hugging Face
        uses: docker/login-action@v3
        with:
          registry: huggingface.co
          username: ${{ secrets.HF_TOKEN_USERNAME }}
          password: ${{ secrets.HF_TOKEN }}

      - name: Build and push Docker image to Hugging Face
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            huggingface.co/mohsin416/visual-products:latest
            huggingface.co/mohsin416/visual-products:${{ github.sha }}