name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git clone https://huggingface.co/spaces/mohsin416/visual-products space
          
          rsync -av --exclude='.git/' --exclude='.github/' --exclude='README.md' ./ space/
          
          cd space
          
          git add .
          git commit -m "Sync from GitHub Actions"
          git push https://username:${HF_TOKEN}@huggingface.co/spaces/mohsin416/visual-products