name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://huggingface.co/spaces/mohsin416/visual-products space
          cd space
          cp -r ../* ./
          git add .
          git commit -m "Sync from GitHub"
          git push https://username:${HF_TOKEN}@huggingface.co/spaces/mohsin416/visual-products