name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

        
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and push Docker image
        run: |
          IMAGE=ghcr.io/mdmohsin212/visual-product-search:latest
          docker build -t $IMAGE .
          docker push $IMAGE


      
      - name: Update Hugging Face Space
        run: |
          git clone https://username:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/mohsin416/visual-products space
          cd space
          echo "FROM ghcr.io/${{ github.repository }}:latest" > Dockerfile
          git add Dockerfile
          git commit -m "Update Space to latest image"
          git push